export const ALL_TEAMS = [
  // IoT
  { teamName: "Vision X", domain: "IoT" },
  { teamName: "Teamcursor101", domain: "IoT" },
  { teamName: "Team Blenders", domain: "IoT" },
  { teamName: "Event Horizon", domain: "IoT" },
  { teamName: "Incredia", domain: "IoT" },
  { teamName: "TEAM CRUSADERS", domain: "IoT" },
  { teamName: "Rhythm", domain: "IoT" },
  { teamName: "IoT Legion's", domain: "IoT" },
  // Cybersecurity
  { teamName: "BinaryBrains", domain: "Cybersecurity" },
  { teamName: "Algorithmics", domain: "Cybersecurity" },
  { teamName: "Vervain", domain: "Cybersecurity" },
  { teamName: "Crib exchanges", domain: "Cybersecurity" },
  { teamName: "Team Dhurandhar", domain: "Cybersecurity" },
  { teamName: "4code", domain: "Cybersecurity" },
  { teamName: "Firewall", domain: "Cybersecurity" },
  { teamName: "Devrush", domain: "Cybersecurity" },
  { teamName: "InnoX", domain: "Cybersecurity" },
  { teamName: "Space syntax", domain: "Cybersecurity" },
  { teamName: "CodeX", domain: "Cybersecurity" },
  { teamName: "Hack-It-Up", domain: "Cybersecurity" },
  { teamName: "Code crafters", domain: "Cybersecurity" },
  // AI/ML
  { teamName: "Tokenizers", domain: "AI/ML" },
  { teamName: "Neural Knights", domain: "AI/ML" },
  { teamName: "Team SPY", domain: "AI/ML" },
  { teamName: "BYTE_FORCE", domain: "AI/ML" },
  { teamName: "Hackzemon", domain: "AI/ML" },
  { teamName: "Spiddy", domain: "AI/ML" },
  { teamName: "Team Prajna", domain: "AI/ML" },
  { teamName: "BrainStack", domain: "AI/ML" },
  { teamName: "CodeShinobis", domain: "AI/ML" },
  { teamName: "VitalSync", domain: "AI/ML" },
  { teamName: "INNOVISION", domain: "AI/ML" },
  { teamName: "WAKANDA'S VISION", domain: "AI/ML" },
  { teamName: "visionauts", domain: "AI/ML" },
  { teamName: "RRCE auralyx", domain: "AI/ML" },
  { teamName: "Chokepoint", domain: "AI/ML" },
  // Open Innovation
  { teamName: "VulnixAI", domain: "Open Innovation" },
  { teamName: "CodeVortex", domain: "Open Innovation" },
  { teamName: "CODEBLASTERS", domain: "Open Innovation" },
  { teamName: "Hexel Studio", domain: "Open Innovation" },
  { teamName: "Team DSA", domain: "Open Innovation" },
  { teamName: "Mossaic", domain: "Open Innovation" },
  { teamName: "Code Ninjas", domain: "Open Innovation" },
  { teamName: "SheSquad", domain: "Open Innovation" },
  { teamName: "Hackoholics", domain: "Open Innovation" },
  { teamName: "Triveni", domain: "Open Innovation" },
  { teamName: "VibeCoders", domain: "Open Innovation" },
  { teamName: "TECH KANNADIGAS", domain: "Open Innovation" },
  { teamName: "Code Blazers", domain: "Open Innovation" },
  { teamName: "Solace", domain: "Open Innovation" },
];
